apiVersion: v1
kind: Service
metadata:
  {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
  name: html-pdf-converter-{{ .DRONE_SOURCE_BRANCH }}
  labels:
    name: html-pdf-converter-{{ .DRONE_SOURCE_BRANCH }}
    role: service
  {{ else }}
  name: html-pdf-converter
  labels:
    name: html-pdf-converter
    role: service
  {{ end }}
spec:
  ports:
  - name: http
    port: 10080
  - name: https
    port: 10443
  selector:
    {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
    name: html-pdf-converter-{{ .DRONE_SOURCE_BRANCH }}
    {{ else }}
    name: html-pdf-converter
    {{ end }}
