pipeline:
  build_6:
    image: node:6
    commands:
      - npm --loglevel warn install
      - npm test
    when:
      event: [push, pull_request]

  build_7:
    image: node:8
    commands:
      - npm --loglevel warn install
      - npm test
    when:
      event: [push, pull_request]

  build_app:
    image: docker:17.09.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -t firearms-$${DRONE_COMMIT_SHA} .
    when:
      event: pull_request

  build_app:
    image: docker:17.09.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -t firearms-$${DRONE_COMMIT_SHA} .
    when:
      branch: master

  build_acceptance:
    image: docker:17.09.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -f Dockerfile-acceptance -t acceptance-$${DRONE_COMMIT_SHA} .
    when:
      event: pull_request

  build_acceptance:
    image: docker:17.09.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -f Dockerfile-acceptance -t acceptance-$${DRONE_COMMIT_SHA} .
    when:
      branch: master

  test_acceptance:
    image: docker:17.09.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker run -e NODE_ENV=ci -e DISABLE_CSP=true -e EMAIL_TRANSPORT=stub -e CASEWORKER_EMAIL=test@example.com -d --net host --userns host firearms-$${DRONE_COMMIT_SHA}
      - docker run --rm --net host --userns host acceptance-$${DRONE_COMMIT_SHA}
    when:
      event: pull_request

  test_acceptance:
    image: docker:17.09.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker run -e NODE_ENV=ci -e DISABLE_CSP=true -e EMAIL_TRANSPORT=stub -e CASEWORKER_EMAIL=test@example.com -d --net host --userns host firearms-$${DRONE_COMMIT_SHA}
      - docker run --rm --net host --userns host acceptance-$${DRONE_COMMIT_SHA}
    when:
      branch: master
      event: push

  image_to_quay:
    image: docker:17.09.1
    secrets:
      - DOCKER_PASSWORD
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker login -u="ukhomeofficedigital+drone" -p=${DOCKER_PASSWORD} quay.io
      - docker tag firearms-$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/firearms:${DRONE_COMMIT_SHA}
      - docker push quay.io/ukhomeofficedigital/firearms:${DRONE_COMMIT_SHA}
    when:
      branch: master
      event: push

  trigger_deploy_to_dev:
    image: quay.io/ukhomeofficedigital/drone-trigger:latest
    secrets:
      - DRONE_TOKEN
    drone_server: https://drone.acp.homeoffice.gov.uk
    repo: UKHomeOffice/kube-firearms
    branch: master
    deploy_to: dev
    params: APP_IMAGE_TAG=${DRONE_COMMIT_SHA},KUBE_NAMESPACE=firearms-dev
    when:
      branch: master
      event: push

  trigger_deploy_to_preprod:
    image: quay.io/ukhomeofficedigital/drone-trigger:latest
    secrets:
      - DRONE_TOKEN
    drone_server: https://drone.acp.homeoffice.gov.uk
    repo: UKHomeOffice/kube-firearms
    branch: master
    deploy_to: preprod
    params: APP_IMAGE_TAG=${DRONE_COMMIT_SHA},KUBE_NAMESPACE=firearms-preprod
    when:
      event: deployment
      environment: preprod

  trigger_deploy_to_prod:
    image: quay.io/ukhomeofficedigital/drone-trigger:latest
    secrets:
      - DRONE_TOKEN
    drone_server: https://drone.acp.homeoffice.gov.uk
    repo: UKHomeOffice/kube-firearms
    branch: master
    deploy_to: prod
    params: APP_IMAGE_TAG=${DRONE_COMMIT_SHA},KUBE_NAMESPACE=firearms
    when:
      event: deployment
      environment: prod

services:
  redis:
    image: redis
