---
kind: pipeline
name: default
type: kubernetes

environment:
  APP_NAME: firearms-licensing
  PROD_ENV: firearms
  STG_ENV: firearms-preprod
  UAT_ENV: firearms-dev
  BRANCH_ENV: firearms-branch
  PRODUCTION_URL: www.firearms-licensing.homeoffice.gov.uk
  IMAGE_URL: quay.io/ukhomeofficedigital
  IMAGE_REPO: firearms
  GIT_REPO: UKHomeOffice/firearms
  HOF_CONFIG: hof-services-config/Firearms_Licensing
  NON_PROD_AVAILABILITY: Mon-Fri 08:00-23:00 Europe/London
  READY_FOR_TEST_DELAY: 20s
  NOTIFY_STUB: stub

trigger:
  branch:
    - feature/*
    - master

steps:
- name: build
  pull: if-not-exists
  image: node:14
  commands:
  - yarn install --frozen-lockfile
  - yarn run postinstall
  - yarn test
  when:
    branch: [ master, feature/* ]
    event: push

- name: build_firearms
  pull: if-not-exists
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
  commands:
  - n=0; while [ "$n" -lt 60 ] && [ ! docker stats --no-stream ]; do n=$(( n + 1 )); sleep 1; done
  - docker build -t firearms-$${DRONE_COMMIT_SHA} .
  when:
    branch: [ master, feature/* ]
    event: push

- name: build_acceptance
  pull: if-not-exists
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
  commands:
  - n=0; while [ "$n" -lt 60 ] && [ ! docker stats --no-stream ]; do n=$(( n + 1 )); sleep 1; done
  - docker build -f Dockerfile-acceptance -t firearms-acceptance-$${DRONE_COMMIT_SHA} .
  when:
    branch: [ master, feature/* ]
    event: push

- name: test_acceptance
  pull: if-not-exists
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
  commands:
  - n=0; while [ "$n" -lt 60 ] && [ ! docker stats --no-stream ]; do n=$(( n + 1 )); sleep 1; done
  - docker run -d --name=firearms-redis-$${DRONE_COMMIT_SHA} redis
  - docker run -d -e NODE_ENV=ci -e DISABLE_CSP=true -e EMAIL_TRANSPORT=stub --net=container:firearms-redis-$${DRONE_COMMIT_SHA} --name=app-$${DRONE_COMMIT_SHA} firearms-$${DRONE_COMMIT_SHA}
  - docker run -d --net=container:app-$${DRONE_COMMIT_SHA} --name=selenium-$${DRONE_COMMIT_SHA} selenium/standalone-chrome
  - sleep 5
  - docker run --rm -e NODE_ENV=ci -e DISABLE_CSP=true -e EMAIL_TRANSPORT=stub --net=container:app-$${DRONE_COMMIT_SHA} firearms-acceptance-$${DRONE_COMMIT_SHA}
  - docker rm -vf "app-$${DRONE_COMMIT_SHA}" "firearms-redis-$${DRONE_COMMIT_SHA}" "selenium-$${DRONE_COMMIT_SHA}"
  when:
    branch: [ master, feature/* ]
    event: push

- name: image_to_quay
  pull: if-not-exists
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
  environment:
    DOCKER_PASSWORD:
      from_secret: DOCKER_PASSWORD
  commands:
  - n=0; while [ "$n" -lt 60 ] && [ ! docker stats --no-stream ]; do n=$(( n + 1 )); sleep 1; done
  - docker login -u="ukhomeofficedigital+drone" -p=$${DOCKER_PASSWORD} quay.io
  - docker tag firearms-$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/firearms:$${DRONE_COMMIT_SHA}
  - docker push quay.io/ukhomeofficedigital/firearms:$${DRONE_COMMIT_SHA}
  when:
    branch: master
    event: push

- name: clone_repos
  image: alpine/git
  environment:
    DRONE_GIT_USERNAME:
      from_secret: DRONE_GIT_USERNAME
    DRONE_GIT_TOKEN:
      from_secret: DRONE_GIT_TOKEN
  commands:
    - git clone https://$${DRONE_GIT_USERNAME}:$${DRONE_GIT_TOKEN}@github.com/UKHomeOfficeForms/hof-services-config.git
  when:
    branch:
      include:
      - master
      - feature/*
    event: [push, pull_request]

- name: clone_repo_promote
  pull: if-not-exists
  image: docker:git
  environment:
    DRONE_GIT_USERNAME:
      from_secret: DRONE_GIT_USERNAME
    DRONE_GIT_TOKEN:
      from_secret: DRONE_GIT_TOKEN
  commands:
    - git clone https://$${DRONE_GIT_USERNAME}:$${DRONE_GIT_TOKEN}@github.com/UKHomeOffice/kube-firearms.git
    - cd kube-firearms
    - git tag ${DRONE_DEPLOY_TO}-${DRONE_COMMIT_SHA}
    - git push origin --tags
  when:
    event: promote
    target: [ preprod, prod ]

- name: deploy_to_dev
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/kd:v1.14.0
  commands:
    - cd kube-firearms
    - bin/deploy.sh
  environment:
    KUBE_SERVER_DEV:
      from_secret: kube_server_dev
    KUBE_TOKEN_DEV:
      from_secret: kube_token_dev
    KUBE_NAMESPACE: firearms-dev
    APP_IMAGE_TAG: ${DRONE_COMMIT_SHA}
  when:
    branch: master
    event: push

- name: deploy_to_preprod
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/kd:v1.14.0
  commands:
    - cd kube-firearms
    - bin/deploy.sh
  environment:
    KUBE_SERVER_DEV:
      from_secret: kube_server_dev
    KUBE_TOKEN_DEV:
      from_secret: kube_token_dev
    KUBE_NAMESPACE: firearms-preprod
    APP_IMAGE_TAG: ${DRONE_COMMIT_SHA}
  when:
    event: promote
    target: preprod

- name: deploy_to_prod
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/kd:v1.14.0
  commands:
    - cd kube-firearms
    - bin/deploy.sh
  environment:
    KUBE_SERVER_PROD:
      from_secret: kube_server_prod
    KUBE_TOKEN_PROD:
      from_secret: kube_token_prod
    KUBE_NAMESPACE: firearms
    APP_IMAGE_TAG: ${DRONE_COMMIT_SHA}
  when:
    event: promote
    target: prod

services:
  - name: docker
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind

...
