instrumentation:
  root: apps
  extensions:
    - .js
  default-excludes: true
  include-all-sources: true
check:
  global:
    statements: 0
    lines: 0
    branches: 0
    functions: 0
reporting:
  print: summary
  reports:
    - html
  dir: ./coverage
  report-config:
    html:
      dir: coverage
