FROM FROM node:24.18.0-alpine3.24@sha256:4ba75f835bb8802193e4c114572113d4b26f95f6f094f4b5229d2a77773e0afc

USER root

# Update packages as a result of security vulnerability checks
RUN apk update && \
    apk add --upgrade gnutls binutils nodejs npm apk-tools libjpeg-turbo libcurl libx11 libxml2

# Setup nodejs group & nodejs user
RUN addgroup --system nodejs --gid 998 && \
    adduser --system nodejs --uid 999 --home /test/ && \
    chown -R 999:998 /test/

USER 999

WORKDIR /test

COPY --chown=999:998 . /test

RUN yarn install --frozen-lockfile && \
    yarn run postinstall

CMD npm run test:acceptance
