version: "2"
services:
  app:
    build: .
    environment:
      - NODE_ENV=development
      - EMAIL_TRANSPORT=smtp
      - EMAIL_HOST=maildev
      - CASEWORKER_EMAIL=caseworker@gov.uk.test
      - IGNORE_TLS=true
      - EMAIL_SECURE=false
      - EMAIL_PORT=25
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - FROM_ADDRESS=caseworker@gov.uk.test
      - AWS_USER=blah
      - AWS_PASSWORD=passwordblah
    links:
      - redis
      - maildev
    ports:
      - "8080:8080"
    volumes:
      - "/public"
  redis:
    image: quay.io/ukhomeofficedigital/redis:v0.1.0

  nginx-proxy:
    image: quay.io/ukhomeofficedigital/nginx-proxy-govuk:v3.0.0.0
    environment:
      - PROXY_SERVICE_HOST=app
      - PROXY_SERVICE_PORT=8080
      - NAXSI_USE_DEFAULT_RULES=FALSE
      - CLIENT_MAX_BODY_SIZE=200
      - ADD_NGINX_SERVER_CFG=add_header Cache-Control private;add_header X-Frame-Options "SAMEORIGIN" always;add_header X-Content-Type-Options "nosniff" always;add_header X-XSS-Protection "1; mode=block" always;location /public {add_header Cache-Control max-age=86400;add_header X-Frame-Options "SAMEORIGIN" always;add_header X-Content-Type-Options "nosniff" always;add_header X-XSS-Protection "1; mode=block" always;alias /public;}
      - ERROR_REDIRECT_CODES=599
    ports:
      - "443:10443"
      - "80:10080"
    links:
      - app
    volumes_from:
      - app

  maildev:
    image: djfarrelly/maildev
    ports:
      - "8000:80"
      - "25"
