FROM node:18-alpine@sha256:2322b1bb3917b313f2e9308395aa5c39d51b91cc92a5d4d5be6d0451fcfb4d24

USER root

# Update packages as a result of Anchore security vulnerability checks
RUN apk update && \
    apk add --upgrade gnutls binutils nodejs npm apk-tools libjpeg-turbo libcurl libx11 libxml2

# Setup nodejs group & nodejs user
RUN addgroup --system nodejs --gid 998 && \
    adduser --system nodejs --uid 999 --home /test/ && \
    chown -R 999:998 /test/

USER 999

WORKDIR /test

COPY --chown=999:998 . /test

RUN yarn install --frozen-lockfile && \
    yarn run postinstall

CMD npm run test:acceptance
