apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: html-pdf-converter-allow-ingress
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: {{ .KUBE_NAMESPACE }}
    ports:
    - port: 10080
      protocol: TCP
    - port: 10443
      protocol: TCP
  podSelector:
    matchLabels:
      name: html-pdf-converter
  policyTypes:
  - Ingress
