apiVersion: v1
kind: Service
metadata:
  name: html-pdf-converter
  labels:
    name: html-pdf-converter
    role: service
spec:
  ports:
  - name: http
    port: 10080
  - name: https
    port: 10443
  selector:
    name: html-pdf-converter
