apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: file-vault-ingress
{{ file .FILEVAULT_INGRESS_EXTERNAL_ANNOTATIONS | indent 2 }}
spec:
  tls:
  - hosts:
    {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
    - fv-branch.{{ .BRANCH_ENV }}.homeoffice.gov.uk
    {{ else if eq .KUBE_NAMESPACE .UAT_ENV }}
    - supp-docs-uat.notprod.{{ .APP_NAME }}.homeoffice.gov.uk
    {{ else if eq .KUBE_NAMESPACE .STG_ENV }}
    - supp-docs-stg.prod.{{ .APP_NAME }}.homeoffice.gov.uk
    {{ else if eq .KUBE_NAMESPACE .PROD_ENV }}
    - supp-docs.prod.{{ .APP_NAME }}.homeoffice.gov.uk
    {{ end }}
    {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
    secretName: branch-tls-external
    {{ else }}
    secretName: file-vault-cert
    {{ end }}
  rules:
  {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
  - host: fv-branch.{{ .BRANCH_ENV }}.homeoffice.gov.uk
  {{ else if eq .KUBE_NAMESPACE .UAT_ENV }}
  - host: supp-docs-uat.notprod.{{ .APP_NAME }}.homeoffice.gov.uk
  {{ else if eq .KUBE_NAMESPACE .STG_ENV }}
  - host: supp-docs-stg.prod.{{ .APP_NAME }}.homeoffice.gov.uk
  {{ else if eq .KUBE_NAMESPACE .PROD_ENV }}
  - host: supp-docs.prod.{{ .APP_NAME }}.homeoffice.gov.uk
  {{ end }}
    http:
      paths:
      - path: /
        backend:
          serviceName: file-vault
          servicePort: 10443
