@firearms
Feature: A user should access the correct service and be able to log an issue

    Scenario: I am on the Museums journey and want to apply for a new authority, there is only one address for storage and I have no purchase order.
        Given I start the 'museums' application journey
        Then I should be on the 'privacy' page showing 'Privacy Notice'
        Then I select 'Continue'
        Then I should be on the 'activity' page showing 'What do you want to do?'
        Then I check 'activity-new'
        Then I select 'Continue'
        Then I should be on the 'name' page showing 'What is the museum\'s name?'
        Then I fill 'name' with 'test museum'
        Then I select 'Continue'
        Then I should be on the 'exhibit-address' page showing 'Where will the firearms be exhibited or stored?'
        Then I fill 'exhibit-postcode' with 'CR0 9YA'
        Then I select 'Find Address'
        Then I should be on the 'exhibit-address-manual' page showing 'Where will the firearms be exhibited or stored?'
        Then I fill 'exhibit-address' text area with 'test address'
        Then I select 'Continue'
        Then I should be on the 'exhibit-add-another-address' page showing 'Is there another address where the firearms will be exhibited or stored?'
        Then I check 'exhibit-addresses-add-another-no'
        Then I select 'Continue'
        Then I should be on the 'contact-name' page showing 'Who should we contact about this application?'
        Then I fill 'contact-name' with 'Ronald Testman'
        Then I select 'Continue'
        Then I should be on the 'contact-details' page showing 'What are their contact details?'
        Then I fill 'contact-email' with 'test@test.com'
        Then I fill 'contact-phone' with '01234567891'
        Then I select 'Continue'
        Then I should be on the 'contact-address' page showing 'Is the contact address the same as an address previously given?'
        Then I check 'same-contact-address-yes'
        Then I select 'Continue'
        Then I should be on the 'contact-address-select' page showing 'Select the contact address'
        Then I choose 'test address'
        Then I select 'Continue'
        Then I should be on the 'invoice-contact-details' page showing 'Who should we contact about the invoice?'
        Then I fill 'invoice-contact-name' with 'ronald testman'
        Then I fill 'invoice-contact-email' with 'test@test.com'
        Then I fill 'invoice-contact-phone' with '01234567891'
        Then I select 'Continue'
        Then I should be on the 'invoice-address-input' page showing 'What is their invoice address?'
        Then I fill 'invoice-postcode' with 'CR0 9YA'
        Then I select 'Find Address'
        Then I should be on the 'invoice-address-input-manual' page showing 'What is their invoice address?'
        Then I fill 'invoice-address' text area with 'test address'
        Then I select 'Continue'
        Then I should be on the 'purchase-order' page showing 'Do you have a purchase order?'
        Then I check 'purchase-order-No'
        Then I select 'Continue'
        Then I should be on the 'confirm' page showing 'Check your answers'
        Then I submit the application
    
    Scenario: I am on the Museums journey and want to apply for a new authority, there are two address for storage and I have no purchase order.
       Given I start the 'museums' application journey
        Then I should be on the 'privacy' page showing 'Privacy Notice'
        Then I select 'Continue'
        Then I should be on the 'activity' page showing 'What do you want to do?'
        Then I check 'activity-new'
        Then I select 'Continue'
        Then I should be on the 'name' page showing 'What is the museum\'s name?'
        Then I fill 'name' with 'test museum'
        Then I select 'Continue'
        Then I should be on the 'exhibit-address' page showing 'Where will the firearms be exhibited or stored?'
        Then I fill 'exhibit-postcode' with 'CR0 9YA'
        Then I select 'Find Address'
        Then I should be on the 'exhibit-address-manual' page showing 'Where will the firearms be exhibited or stored?'
        Then I fill 'exhibit-address' text area with 'test address'
        Then I select 'Continue'
        Then I should be on the 'exhibit-add-another-address' page showing 'Is there another address where the firearms will be exhibited or stored?'
        Then I check 'exhibit-addresses-add-another-yes'
        Then I select 'Continue'
        Then I should be on the 'exhibit-address' page showing 'Where will the firearms be exhibited or stored?'
        Then I fill 'exhibit-postcode' with 'CR0 9YB'
        Then I select 'Find Address'
        Then I should be on the 'exhibit-address-manual' page showing 'Where will the firearms be exhibited or stored?'
        Then I fill 'exhibit-address' text area with 'test address 2'
        Then I select 'Continue'
        Then I should be on the 'exhibit-add-another-address' page showing 'Is there another address where the firearms will be exhibited or stored?'
        Then I check 'exhibit-addresses-add-another-no'
        Then I select 'Continue'
        Then I should be on the 'contact-name' page showing 'Who should we contact about this application?'
        Then I fill 'contact-name' with 'Ronald Testman'
        Then I select 'Continue'
        Then I should be on the 'contact-details' page showing 'What are their contact details?'
        Then I fill 'contact-email' with 'test@test.com'
        Then I fill 'contact-phone' with '01234567891'
        Then I select 'Continue'
        Then I should be on the 'contact-address' page showing 'Is the contact address the same as an address previously given?'
        Then I check 'same-contact-address-yes'
        Then I select 'Continue'
        Then I should be on the 'contact-address-select' page showing 'Select the contact address'
        Then I choose 'test address'
        Then I select 'Continue'
        Then I should be on the 'invoice-contact-details' page showing 'Who should we contact about the invoice?'
        Then I fill 'invoice-contact-name' with 'ronald testman'
        Then I fill 'invoice-contact-email' with 'test@test.com'
        Then I fill 'invoice-contact-phone' with '01234567891'
        Then I select 'Continue'
        Then I should be on the 'invoice-address-input' page showing 'What is their invoice address?'
        Then I fill 'invoice-postcode' with 'CR0 9YA'
        Then I select 'Find Address'
        Then I should be on the 'invoice-address-input-manual' page showing 'What is their invoice address?'
        Then I fill 'invoice-address' text area with 'test address'
        Then I select 'Continue'
        Then I should be on the 'purchase-order' page showing 'Do you have a purchase order?'
        Then I check 'purchase-order-No'
        Then I select 'Continue'
        Then I should be on the 'confirm' page showing 'Check your answers'
        Then I submit the application

    Scenario: I am on the Museums journey and want to apply for a new authority, there is only one address for storage but do have a purchase order.
        Given I start the 'museums' application journey
        Then I should be on the 'privacy' page showing 'Privacy Notice'
        Then I select 'Continue'
        Then I should be on the 'activity' page showing 'What do you want to do?'
        Then I check 'activity-new'
        Then I select 'Continue'
        Then I should be on the 'name' page showing 'What is the museum\'s name?'
        Then I fill 'name' with 'test museum'
        Then I select 'Continue'
        Then I should be on the 'exhibit-address' page showing 'Where will the firearms be exhibited or stored?'
        Then I fill 'exhibit-postcode' with 'CR0 9YA'
        Then I select 'Find Address'
        Then I should be on the 'exhibit-address-manual' page showing 'Where will the firearms be exhibited or stored?'
        Then I fill 'exhibit-address' text area with 'test address'
        Then I select 'Continue'
        Then I should be on the 'exhibit-add-another-address' page showing 'Is there another address where the firearms will be exhibited or stored?'
        Then I check 'exhibit-addresses-add-another-no'
        Then I select 'Continue'
        Then I should be on the 'contact-name' page showing 'Who should we contact about this application?'
        Then I fill 'contact-name' with 'Ronald Testman'
        Then I select 'Continue'
        Then I should be on the 'contact-details' page showing 'What are their contact details?'
        Then I fill 'contact-email' with 'test@test.com'
        Then I fill 'contact-phone' with '01234567891'
        Then I select 'Continue'
        Then I should be on the 'contact-address' page showing 'Is the contact address the same as an address previously given?'
        Then I check 'same-contact-address-yes'
        Then I select 'Continue'
        Then I should be on the 'contact-address-select' page showing 'Select the contact address'
        Then I choose 'test address'
        Then I select 'Continue'
        Then I should be on the 'invoice-contact-details' page showing 'Who should we contact about the invoice?'
        Then I fill 'invoice-contact-name' with 'ronald testman'
        Then I fill 'invoice-contact-email' with 'test@test.com'
        Then I fill 'invoice-contact-phone' with '01234567891'
        Then I select 'Continue'
        Then I should be on the 'invoice-address-input' page showing 'What is their invoice address?'
        Then I fill 'invoice-postcode' with 'CR0 9YA'
        Then I select 'Find Address'
        Then I should be on the 'invoice-address-input-manual' page showing 'What is their invoice address?'
        Then I fill 'invoice-address' text area with 'test address'
        Then I select 'Continue'
        Then I should be on the 'purchase-order' page showing 'Do you have a purchase order?'
        Then I check 'purchase-order-Yes'
        Then I fill 'purchase-order-number' with 'PO123'
        Then I select 'Continue'
        Then I should be on the 'confirm' page showing 'Check your answers'
        Then I submit the application
        
    Scenario: I am on the Museums journey and want to renew an existing authority
        Given I start the 'museums' application journey
        Then I should be on the 'privacy' page showing 'Privacy Notice'
        Then I select 'Continue'
        Then I should be on the 'activity' page showing 'What do you want to do?'
        Then I check 'activity-renew'
        Then I select 'Continue'
        Then I should be on the 'existing-authority' page showing 'Upload existing authority documents'
        Then I upload the 'testPath/test.pdf' file to 'existing-authority-upload'
        #The test below is currently a cheat as it skips a page. See steps.js
        Then I pick 'Upload file' to go to the 'existing-authority-add-another' page
        Then I should be on the 'name' page showing 'What is the museum\'s name?'
        Then I fill 'name' with 'test museum'
        Then I select 'Continue'
        Then I should be on the 'exhibit-address' page showing 'Where will the firearms be exhibited or stored?'
        Then I fill 'exhibit-postcode' with 'AB12 1ab'
        Then I select 'Find Address'
        Then I should be on the 'exhibit-address-manual' page showing 'Where will the firearms be exhibited or stored?'
        Then I fill 'exhibit-address' text area with 'test address'
        Then I select 'Continue'
        Then I should be on the 'exhibit-add-another-address' page showing 'Is there another address where the firearms will be exhibited or stored?'
        Then I check 'exhibit-addresses-add-another-no'
        Then I select 'Continue'
        Then I should be on the 'contact-name' page showing 'Who should we contact about this application?'
        Then I fill 'contact-name' with 'Ronald Testman'
        Then I select 'Continue'
        Then I should be on the 'contact-details' page showing 'What are their contact details?'
        Then I fill 'contact-email' with 'test@test.com'
        Then I fill 'contact-phone' with '01234567891'
        Then I select 'Continue'
        Then I should be on the 'contact-address' page showing 'Is the contact address the same as an address previously given?'
        Then I check 'same-contact-address-yes'
        Then I select 'Continue'
        Then I should be on the 'contact-address-select' page showing 'Select the contact address'
        Then I choose 'test address'
        Then I select 'Continue'
        Then I should be on the 'invoice-contact-details' page showing 'Who should we contact about the invoice?'
        Then I fill 'invoice-contact-name' with 'ronald testman'
        Then I fill 'invoice-contact-email' with 'test@test.com'
        Then I fill 'invoice-contact-phone' with '01234567891'
        Then I select 'Continue'
        Then I should be on the 'invoice-address-input' page showing 'What is their invoice address?'
        Then I fill 'invoice-postcode' with 'CR0 9YA'
        Then I select 'Find Address'
        Then I should be on the 'invoice-address-input-manual' page showing 'What is their invoice address?'
        Then I fill 'invoice-address' text area with 'test address'
        Then I select 'Continue'
        Then I should be on the 'purchase-order' page showing 'Do you have a purchase order?'
        Then I check 'purchase-order-Yes'
        Then I fill 'purchase-order-number' with 'PO123'
        Then I select 'Continue'
        Then I should be on the 'confirm' page showing 'Check your answers'
        Then I submit the application

    Scenario: I am on the Museums journey and want to amend an existing authority
        Given I start the 'museums' application journey
        Then I should be on the 'privacy' page showing 'Privacy Notice'
        Then I select 'Continue'
        Then I should be on the 'activity' page showing 'What do you want to do?'
        Then I check 'activity-vary'
        Then I select 'Continue'
        Then I should be on the 'existing-authority' page showing 'Upload existing authority documents'
        Then I upload the 'testPath/test.pdf' file to 'existing-authority-upload'
        #The test below is currently a cheat as it skips a page. See steps.js
        Then I pick 'Upload file' to go to the 'existing-authority-add-another' page
        Then I should be on the 'name' page showing 'What is the museum\'s name?'
        Then I fill 'name' with 'test museum'
        Then I select 'Continue'
        Then I should be on the 'exhibit-address' page showing 'Where will the firearms be exhibited or stored?'
        Then I fill 'exhibit-postcode' with 'AB12 1ab'
        Then I select 'Find Address'
        Then I should be on the 'exhibit-address-manual' page showing 'Where will the firearms be exhibited or stored?'
        Then I fill 'exhibit-address' text area with 'test address'
        Then I select 'Continue'
        Then I should be on the 'exhibit-add-another-address' page showing 'Is there another address where the firearms will be exhibited or stored?'
        Then I check 'exhibit-addresses-add-another-no'
        Then I select 'Continue'
        Then I should be on the 'contact-name' page showing 'Who should we contact about this application?'
        Then I fill 'contact-name' with 'Ronald Testman'
        Then I select 'Continue'
        Then I should be on the 'contact-details' page showing 'What are their contact details?'
        Then I fill 'contact-email' with 'test@test.com'
        Then I fill 'contact-phone' with '01234567891'
        Then I select 'Continue'
        Then I should be on the 'contact-address' page showing 'Is the contact address the same as an address previously given?'
        Then I check 'same-contact-address-yes'
        Then I select 'Continue'
        Then I should be on the 'contact-address-select' page showing 'Select the contact address'
        Then I choose 'test address'
        Then I select 'Continue'
        Then I should be on the 'invoice-contact-details' page showing 'Who should we contact about the invoice?'
        Then I fill 'invoice-contact-name' with 'ronald testman'
        Then I fill 'invoice-contact-email' with 'test@test.com'
        Then I fill 'invoice-contact-phone' with '01234567891'
        Then I select 'Continue'
        Then I should be on the 'invoice-address-input' page showing 'What is their invoice address?'
        Then I fill 'invoice-postcode' with 'CR0 9YA'
        Then I select 'Find Address'
        Then I should be on the 'invoice-address-input-manual' page showing 'What is their invoice address?'
        Then I fill 'invoice-address' text area with 'test address'
        Then I select 'Continue'
        Then I should be on the 'purchase-order' page showing 'Do you have a purchase order?'
        Then I check 'purchase-order-Yes'
        Then I fill 'purchase-order-number' with 'PO123'
        Then I select 'Continue'
        Then I should be on the 'confirm' page showing 'Check your answers'
        Then I submit the application

    Scenario: I am on the New-dealer journey and want to apply for a new authority
        Given I start the 's5' application journey
        Then I should be on the 'privacy' page showing 'Privacy Notice'
        Then I select 'Continue'
        Then I should be on the 'before-you-start' page showing 'Before you start'
        Then I select 'Continue'
        Then I should be on the 'activity' page showing 'What do you want to do?'
        Then I check 'activity-new'
        Then I select 'Continue'
        Then I should be on the 'supporting-documents' page showing 'Upload your supporting documents'
        Then I upload the 'testPath/test.pdf' file to 'supporting-document-upload'
        Then I pick 'Upload file' to go to the 'supporting-documents-add-another' page
        Then I should be on the 'supporting-documents-add-another' page showing 'Upload your supporting documents'
        #CANNOT PROCEED WITHOUT SECURTIY DETAILS...

    #ALL S5 CURRENTLY UNDER WORK
    Scenario: I am on the New-dealer journey and want to amend an exixting authority
        Given I start the 's5' application journey
        Then I should be on the 'privacy' page showing 'Privacy Notice'
        Then I select 'Continue'
        Then I should be on the 'before-you-start' page showing 'Before you start'
        Then I select 'Continue'
        Then I should be on the 'activity' page showing 'What do you want to do?'
        Then I check 'activity-renew'
        Then I select 'Continue'
        Then I should be on the 'existing-authority' page showing 'Upload existing authority documents'
        Then I upload the 'testPath/test.pdf' file to 'existing-authority-upload'
        #The test below is currently a cheat as it skips a page. See steps.js
        Then I pick 'Upload file' to go to the 'supporting-documents' page
        Then I should be on the 'supporting-documents' page showing 'Upload your supporting documents'
        Then I upload the 'testPath/test.pdf' file to 'supporting-document-upload'
        Then I pick 'Upload file' to go to the 'supporting-documents-add-another' page
        Then I should be on the 'supporting-documents-add-another' page showing 'Upload your supporting documents'
       #CANNOT PROCEED WITHOUT SECURTIY DETAILS...

    Scenario: I am on the New-dealer journey and want to amend an exixting authority
        Given I start the 's5' application journey
        Then I should be on the 'privacy' page showing 'Privacy Notice'
        Then I select 'Continue'
        Then I should be on the 'before-you-start' page showing 'Before you start'
        Then I select 'Continue'
        Then I should be on the 'activity' page showing 'What do you want to do?'
        Then I check 'activity-vary'
        Then I select 'Continue'
        Then I should be on the 'existing-authority' page showing 'Upload existing authority documents'
        Then I upload the 'testPath/test.pdf' file to 'existing-authority-upload'
        #The test below is currently a cheat as it skips a page. See steps.js
        Then I pick 'Upload file' to go to the 'supporting-documents' page
        Then I should be on the 'supporting-documents' page showing 'Upload your supporting documents'
        Then I upload the 'testPath/test.pdf' file to 'supporting-document-upload'
        Then I pick 'Upload file' to go to the 'supporting-documents-add-another' page
        Then I should be on the 'supporting-documents-add-another' page showing 'Upload your supporting documents'
       #CANNOT PROCEED WITHOUT SECURTIY DETAILS...

    Scenario: I am on the Shooting-clubs journey and want to amend an exixting authority
        Given I start the 'shooting-clubs' application journey
        Then I should be on the 'privacy' page showing 'Privacy Notice'
        Then I select 'Continue'
        Then I should be on the 'activity' page showing 'What do you want to do?'
        Then I check 'activity-new'
        Then I select 'Continue'
        Then I should be on the 'new-club' page showing 'Is the club a new club?'
        Then I check 'new-club-yes'
        Then I select 'Continue'
        Then I should be on the 'club-name' page showing 'What is the club\'s name?'
        Then I fill 'club-name' with 'test club'
        Then I select 'Continue'
        Then I should be on the 'club-address' page showing 'What is the club\'s address?'
        Then I fill 'club-postcode' with 'CR0 9YA'
        Then I select 'Find Address'
        Then I should be on the 'club-address-manual' page showing 'What is the club\'s address?'
        Then I fill 'club-address' text area with 'test address 1'
        Then I select 'Continue'
        Then I should be on the 'club-secretary-name' page showing 'What is the club secretary\'s name?'
        Then I fill 'club-secretary-name' with 'Ronald Testman'
        Then I select 'Continue'
        Then I should be on the 'club-secretary-address' page showing 'What is Ronald Testman\'s contact address?'
        Then I fill 'club-secretary-postcode' with 'CR0 9YA'
        Then I select 'Find Address'
        Then I should be on the 'club-secretary-address-manual' page showing 'What is Ronald Testman\'s contact address?'
        Then I fill 'club-secretary-address' text area with 'test address 2'
        Then I select 'Continue'
        Then I should be on the 'club-secretary-email' page showing 'What are Ronald Testman\'s contact details?'
        Then I fill 'club-secretary-email' with 'test@test.com'
        Then I fill 'club-secretary-phone' with '01234567890'
        Then I select 'Continue'
        Then I should be on the 'second-contact-name' page showing 'Who should we contact in Ronald Testman\'s absence?'
        Then I fill 'second-contact-name' with 'Donald Testman'
        Then I select 'Continue'
        Then I should be on the 'second-contact-address' page showing 'What is Donald Testman\'s contact address?'
        Then I fill 'second-contact-postcode' with 'CR0 9YA'
        Then I select 'Find Address'
        Then I should be on the 'second-contact-address-manual' page showing 'What is Donald Testman\'s contact address?'
        Then I fill 'second-contact-address' text area with 'test address 3'
        Then I select 'Continue'
        Then I should be on the 'second-contact-email' page showing 'What are Donald Testman\'s contact details?'
        Then I fill 'second-contact-email' with 'donald@test.com'
        Then I fill 'second-contact-phone' with '01234567890'
        Then I select 'Continue'
        Then I should be on the 'location-address' page showing 'Which shooting ranges will the club use?'
        Then I fill 'location-postcode' with 'cr0 9YA'
        Then I select 'Find Address'
        Then I should be on the 'location-address-manual' page showing 'Which shooting ranges will the club use?'
        Then I fill 'location-address' text area with 'test address 4'
        Then I select 'Continue'
        Then I should be on the 'location-address-category' page showing 'Which categories of firearms will be used at this range?'
        Then I check 'location-address-category-full-bore-rifles'
        Then I select 'Continue'
        Then I should be on the 'location-add-another-address' page showing 'Will the club use another shooting range?'
        Then I check 'location-addresses-add-another-no'
        Then I select 'Continue'
        Then I should be on the 'storage-address' page showing 'At which of these addresses, if any, will the firearms be stored?'
        Then I select 'Continue'
        Then I should be on the 'storage-add-another-address' page showing 'Is there another address where the guns will be stored?'
        Then I check 'all-storage-addresses-add-another-no'
        Then I select 'Continue'
        Then I should be on the 'invoice-contact-details' page showing 'Who should we contact about the invoice?'
        Then I fill 'invoice-contact-name' with 'Ronald Testman'
        Then I fill 'invoice-contact-email' with 'ronald@testman.com'
        Then I fill 'invoice-contact-phone' with '01234567898'
        Then I select 'Continue'
        Then I should be on the 'invoice-address-input' page showing 'What is their invoice address?'
        Then I fill 'invoice-postcode' with 'CR0 9YA'
        Then I select 'Find Address'
        Then I should be on the 'invoice-address-input-manual' page showing 'What is their invoice address?'
        Then I fill 'invoice-address' text area with 'Test invoice address'
        Then I select 'Continue'
        Then I should be on the 'purchase-order' page showing 'Do you have a purchase order?'
        Then I check 'purchase-order-No'
        Then I select 'Continue'
        Then I should be on the 'confirm' page showing 'Check your answers'
        Then I select 'Continue'

    @feature 
    Scenario: I am on the Shooting-clubs journey and want to renew an exixting authority
        Given I start the 'shooting-clubs' application journey
        Then I should be on the 'privacy' page showing 'Privacy Notice'
        Then I select 'Continue'
        Then I should be on the 'activity' page showing 'What do you want to do?'
        Then I check 'activity-renew'
        Then I select 'Continue'
        Then I should be on the 'existing-authority' page showing 'Upload existing authority documents'
        Then I upload the 'testPath/test.pdf' file to 'existing-authority-upload'
        Then I pick 'Upload file' to go to the 'existing-authority-add-another' page
        Then I should be on the 'existing-authority-add-another' page showing 'Do you want to upload any additional existing authority documents to support your application?'
        Then I check 'existing-authority-add-another-no'
        Then I select 'Continue'